protected/controllers/GalleryController.php
<?php
/**
 * Created by IntelliJ IDEA.
 * User: Demin
 * Date: 08.08.13
 * Time: 23:23
 * To change this template use File | Settings | File Templates.
 */
require_once 'PostController.php';
class GalleryController  extends PostController {

    /**
     * @param CDbCriteria $criteria
     * @return mixed
     */
    protected function loadCriteria($criteria){
        $criteria->addCondition('is_gallery = 1');
        return $criteria;
    }
}

protected/controllers/PostController.php
<?php

class PostController extends Controller
{
	public $layout='morr_windowed';


	/**
	 * @var CActiveRecord the currently loaded data model instance.
	 */
	private $_model;

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to access 'index' and 'view' actions.
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated users to access all actions
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 */
	public function actionView()
	{
		$post=$this->loadModel();

		$this->render('view',array(
			'model'=>$post,
		));
	}


	public function actionIndex()
	{
		$criteria=new CDbCriteria(array(
			'condition'=>'status='.Post::STATUS_PUBLISHED,
			'order'=>'update_time DESC',
		));
        $now = new CDbExpression("NOW()");
        $criteria->addCondition('date_active_from < "'.$now.'" ');
		if(isset($_GET['tag']))
			$criteria->addSearchCondition('tags',$_GET['tag']);
        $criteria = $this->loadCriteria($criteria);
		$dataProvider=new CActiveDataProvider('Post', array(
			'pagination'=>array(
				'pageSize'=>Yii::app()->params['postsPerPage'],
			),
			'criteria'=>$criteria,
		));

		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}


	/**
	 * Suggests tags based on the current user input.
	 * This is called via AJAX when the user is entering the tags input.
	 */
	public function actionSuggestTags()
	{
		if(isset($_GET['q']) && ($keyword=trim($_GET['q']))!=='')
		{
			$tags=Tag::model()->suggestTags($keyword);
			if($tags!==array())
				echo implode("\n",$tags);
		}
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 */
	public function loadModel()
	{
		if($this->_model===null)
		{
			if(isset($_GET['id']))
			{
				if(Yii::app()->user->isGuest)
					$condition='status='.Post::STATUS_PUBLISHED.' OR status='.Post::STATUS_ARCHIVED;
				else
					$condition='';
				$this->_model=Post::model()->findByPk($_GET['id'], $condition);
			}
			if($this->_model===null)
				throw new CHttpException(404,'The requested page does not exist.');
		}
		return $this->_model;
	}

    /**
     * @param CDbCriteria $criteria
     * @return mixed
     */
    protected function loadCriteria($criteria){
        return $criteria;
    }


}

protected/views/layouts/morr_onecolumn.php
<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru">
<head>
    <link rel="icon" type="image/x-icon" href="<?php echo Yii::app()->request->baseUrl; ?>/favicon.png"/>
    <link rel="shortcut icon" type="image/x-icon" href="<?php echo Yii::app()->request->baseUrl; ?>/favicon.png"/>
    <?php
        $cs = Yii::app()->getClientScript();
        $cs->registerCoreScript('jquery');
        //$cs->registerScriptFile(Yii::app()->request->baseUrl.'/import/lightbox/js/lightbox-2.6.min.js', CClientScript::POS_END);
    ?>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo CHtml::encode($this->pageTitle); ?></title>
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/import/css/style.css" type="text/css" rel="stylesheet" media="all"/>
    <link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/import/fonts/stylesheet.css" type="text/css" charset="utf-8" />
    <!--[if lt IE 7]>
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/import/css/style_ie6.css" type="text/css" rel="stylesheet" media="all"/>
    <![endif]-->
    <!--[if IE 7]>
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/import/css/style_ie7.css" type="text/css" rel="stylesheet" media="all"/>
    <![endif]-->
    <!--[if IE 8]>
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/import/css/style_ie8.css" type="text/css" rel="stylesheet" media="all"/>
    <![endif]-->
    <!--[if IE 9]>
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/import/css/style_ie9.css" type="text/css" rel="stylesheet" media="all"/>
    <![endif]-->
    <!--[if IE 10]>
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/import/css/style_ie10.css" type="text/css" rel="stylesheet" media="all"/>
    <![endif]-->
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/import/lightbox/css/lightbox.css" rel="stylesheet" />

    <style>

    </style>

</head>

<body>
<div id="index">

    <div id="index-top" class='center main-width'>
        <div id="main-underlayer" class='wrp center main-width bg80'>
            <div class='top border'></div>
            <div class='top left border'></div>
            <div class='top right border'></div>
            <div class='left border'></div>
            <div class='right border'></div>
            <div class='bottom left border'></div>
            <div class='bottom right border'></div>
            <div class='bottom border'></div>
        </div>
        <div id="maxwidther" class="main-width center">
            <div id="header">
                <a href="/" class='logo'><img src="<?php echo Yii::app()->request->baseUrl; ?>/import/i/shrift.png" alt="На главную"></a>
                <div id='mainmenu'>
                    <?php $this->widget('zii.widgets.CMenu',array(
                        'items'=>array(
                            array('label'=>Yii::t('main','Home'), 'url'=>array('post/index')),
                            array('label'=>Yii::t('main','About'), 'url'=>array('site/page', 'view'=>'about')),
                            array('label'=>Yii::t('main','Gallery'), 'url'=>array('gallery/list')),
                            array('label'=>Yii::t('main','Contact'), 'url'=>array('site/contact')),
                            array('label'=>Yii::t('main','Forum'), 'url'=>'http://forum.gardarike.org/viewforum.php?f=109'),
                        ),
                    )); ?>
                </div>
            </div>
            <div id="content">


                <?php echo $content; ?>


            </div>

            <div class='ca'></div>
        </div>
    </div>
    <div id="foot">
        <div id="footwidther" class='main-width'>
            <?php echo Yii::powered(); ?>
        </div>
    </div>
</div>
</body>
</html>

protected/views/layouts/morr_twocolumn.php
<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru">
<head>
    <link rel="icon" type="image/x-icon" href="/favicon.ico"/>
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico"/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Test</title>
    <link href="import/css/style.css" type="text/css" rel="stylesheet" media="all"/>
    <link rel="stylesheet" href="import/fonts/stylesheet.css" type="text/css" charset="utf-8" />
    <!--[if lt IE 7]>
    <link href="import/css/style_ie6.css" type="text/css" rel="stylesheet" media="all"/>
    <![endif]-->
    <!--[if IE 7]>
    <link href="import/css/style_ie7.css" type="text/css" rel="stylesheet" media="all"/>
    <![endif]-->
    <!--[if IE 8]>
    <link href="import/css/style_ie8.css" type="text/css" rel="stylesheet" media="all"/>
    <![endif]-->
    <!--[if IE 9]>
    <link href="import/css/style_ie9.css" type="text/css" rel="stylesheet" media="all"/>
    <![endif]-->
    <!--[if IE 10]>
    <link href="import/css/style_ie10.css" type="text/css" rel="stylesheet" media="all"/>
    <![endif]-->

    <style>

    </style>

</head>

<body>
<div id="index">

    <div id="index-top" class='center main-width'>
        <div id="main-underlayer" class='wrp center main-width'>
            <div id="content-underlayer" class='wrp'>
                <div class='top border'></div>
                <div class='top left border'></div>
                <div class='top right border'></div>
                <div class='left border'></div>
                <div class='right border'></div>
                <div class='bottom left border'></div>
                <div class='bottom right border'></div>
                <div class='bottom border'></div>
            </div>
            <div id="sidebar-underlayer" class='wrp'>
                <div class='top border'></div>
                <div class='top left border'></div>
                <div class='top right border'></div>
                <div class='left border'></div>
                <div class='right border'></div>
                <div class='bottom left border'></div>
                <div class='bottom right border'></div>
                <div class='bottom border'></div>
            </div>
        </div>
        <div id="maxwidther" class="main-width center">
            <div id="header">
                <a href="/" class='logo'><img src="import/i/shrift.png" alt="На главную"></a>
                <div id='mainmenu'>
                    <ul>
                        <li class='active'><a href="/">Главная</a></li>
                        <li ><a href="/onecolumn.html" >О проекте</a></li>
                        <li><a href="#" >Галерея</a></li>
                        <li><a href="#" >Контакты</a></li>
                        <li><a href="http://forum.gardarike.org/viewforum.php?f=109" >Форум</a></li>
                    </ul>
                </div>
            </div>

            <div id="container">

                <div id="content">
                    <div class="center block-name">Лента</div>
                    Content    <br/>
                    Content    <br/>
                    Content    <br/>
                    Content    <br/>
                    Content    <br/>
                    Content    <br/>
                    Content    <br/>
                    Content    <br/>
                    Content    <br/>
                    Content    <br/>
                    Content    <br/>
                    Content    <br/>
                    Content    <br/>
                    Content    <br/>
                </div>
            </div>
            <div id="sidebar">
                <div class="center block-name">Меню</div>
                Sidebar
            </div>
            <div class='ca'></div>
        </div>
    </div>
    <div id="foot">
        <div id="footwidther" class='main-width'>

        </div>
    </div>
</div>
</body>
</html>

protected/views/layouts/morr_windowed.php
<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru">
<head>
    <link rel="icon" type="image/x-icon" href="<?php echo Yii::app()->request->baseUrl; ?>/favicon.png"/>
    <link rel="shortcut icon" type="image/x-icon" href="<?php echo Yii::app()->request->baseUrl; ?>/favicon.png"/>
    <?php
        $cs = Yii::app()->getClientScript();
        $cs->registerCoreScript('jquery');
        $cs->registerScriptFile(Yii::app()->request->baseUrl.'/import/lightbox/js/lightbox.min.js', CClientScript::POS_END);
        $cs->registerScriptFile(Yii::app()->request->baseUrl.'/import/js/main.js', CClientScript::POS_END);
    ?>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo CHtml::encode($this->pageTitle); ?></title>
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/import/css/style.css" type="text/css" rel="stylesheet" media="all"/>
    <link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/import/fonts/stylesheet.css" type="text/css" charset="utf-8" />
    <link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/import/lightbox/css/lightbox.css" type="text/css" charset="utf-8" />
    <!--[if lt IE 7]>
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/import/css/style_ie6.css" type="text/css" rel="stylesheet" media="all"/>
    <![endif]-->
    <!--[if IE 7]>
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/import/css/style_ie7.css" type="text/css" rel="stylesheet" media="all"/>
    <![endif]-->
    <!--[if IE 8]>
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/import/css/style_ie8.css" type="text/css" rel="stylesheet" media="all"/>
    <![endif]-->
    <!--[if IE 9]>
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/import/css/style_ie9.css" type="text/css" rel="stylesheet" media="all"/>
    <![endif]-->
    <!--[if IE 10]>
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/import/css/style_ie10.css" type="text/css" rel="stylesheet" media="all"/>
    <![endif]-->
    <style>

    </style>

</head>

<body>
<div id="index">

    <div id="index-top" class='center main-width'>
        <div id="main-underlayer" class='wrp center main-width'>
            <div id="content-underlayer" class='wrp'>
                <div class='top border'></div>
                <div class='top left border'></div>
                <div class='top right border'></div>
                <div class='left border'></div>
                <div class='right border'></div>
                <div class='bottom left border'></div>
                <div class='bottom right border'></div>
                <div class='bottom border'></div>
            </div>
            <div id="sidebar-underlayer bgnone" class='wrp'>

            </div>
        </div>
        <div id="maxwidther" class="main-width center">
            <div id="header">
                <div class="lang">
                    <a href="<?php echo $this->createUrl(Yii::app()->request->pathInfo,array('lang'=>'ru'))?>">RU</a> /
                    <a href="<?php echo $this->createUrl(Yii::app()->request->pathInfo,array('lang'=>'en'))?>">EN</a>
                </div>
                <a href="/" class='logo'><img src="<?php echo Yii::app()->request->baseUrl; ?>/import/i/shrift.png" alt="На главную"></a>
                <div id='mainmenu'>
                    <?php $this->widget('zii.widgets.CMenu',array(
                        'items'=>array(
                            array('label'=>Yii::t('main','Home'), 'url'=>array('post/index')),
                            array('label'=>Yii::t('main','About'), 'url'=>array('site/page', 'view'=>'about')),
                            array('label'=>Yii::t('main','Gallery'), 'url'=>array('gallery/index')),
                            array('label'=>Yii::t('main','Contact'), 'url'=>array('site/page', 'view'=>'contact')),
                            array('label'=>Yii::t('main','Forum'), 'url'=>'http://forum.gardarike.org/viewforum.php?f=109'),
                        ),
                    )); ?>
                </div>
            </div>

            <div id="container">

                <div id="content">
                    <div class="center block-name"><?php echo Yii::t('main','News')?></div>
                    <?php echo $content; ?>
                </div>
            </div>
            <div id="sidebar" class='windowed'>
                <div class="window bg80 menu">
                    <div class='top border'><div class="center block-name"><?php echo Yii::t('main','Menu')?></div></div>
                    <div class='top left border'></div>
                    <div class='top right border'></div>
                    <div class='left border'></div>
                    <div class='right border'></div>
                    <div class='bottom left border'></div>
                    <div class='bottom right border'></div>
                    <div class='bottom border'></div>
                    <div class="window-content">
                        <?php $this->widget('UserMenu', array()); ?>
                    </div>
                </div>
                <br>
                <div class="window bg80">
                    <div class='top border'><div class="center block-name"><?php echo Yii::t('main','Tags')?></div></div>
                    <div class='top left border'></div>
                    <div class='top right border'></div>
                    <div class='left border'></div>
                    <div class='right border'></div>
                    <div class='bottom left border'></div>
                    <div class='bottom right border'></div>
                    <div class='bottom border'></div>
                    <div class="window-content">


                        <?php $this->widget('TagCloud', array(
                            'maxTags'=>Yii::app()->params['tagCloudCount'],
                        )); ?>
                    </div>
                </div>
            </div>
            <div class='ca'></div>
        </div>
    </div>
    <div id="foot">
        <div id="footwidther" class='main-width'>
            <?php echo Yii::powered(); ?>
        </div>
    </div>
</div>
</body>
</html>